- hosts: localhost
  tasks:

    - name: Install pip2 packages
      pip:
        name: [
          "neovim",
          "python-language-server"
        ]
        executable: "pip2"
        state: "present"

    - name: Install pip3 packages
      pip:
        name: [
          "neovim",
          "python-language-server"
        ]
        executable: "pip3"
        state: "present"

    - name: "Check if ~/.cargo/env file exists"
      stat: 
        path: "~/.cargo/env"
      register: cargo_env_file

    - name: "Download rustup script"
      get_url:
        url: "https://sh.rustup.rs"
        dest: "/tmp/ansible-downloads-rustup.rs"
      register: rustup_download

    - name: "Run rustup script"
      command: "sh /tmp/ansible-downloads-rustup.rs -y"
      register: rustup_install
      when: rustup_download.changed or cargo_env_file.stat.exists == False

