- hosts: localhost
  tasks:
    - homebrew_tap:
        name: "d12frosted/emacs-plus"
        state: present
    - name: install go
      homebrew:
        name: "go"
        state: present
    - name: install yarn
      homebrew:
        name: "yarn"
        state: present
    - name: install vim
      homebrew:
        name: "vim"
        state: present
    - name: install neovim
      homebrew:
        name: "neovim"
        state: present
    - name: install emacs-plus
      homebrew:
        name: "emacs-plus"
        state: present
    - name: install tmux
      homebrew:
        name: "tmux"
        state: present
    - name: install tfenv
      homebrew:
        name: "tfenv"
        state: present
    - name: install kubectl
      homebrew:
        name: "kubectl"
        state: present
    - name: install kubectx
      homebrew:
        name: "kubectx"
        state: present
    - name: install missionctl
      pip:
        name: missionctl
        state: present
