- hosts: localhost
  tasks:
    # - name: add emacs tap
    #   homebrew_tap:
    #     name: "d12frosted/emacs-plus"
    #     state: present
    - name: install watch
      homebrew:
        name: "watch"
        state: present
    - name: install node
      homebrew:
        name: "node"
        state: present
    - name: install yarn
      homebrew:
        name: "yarn"
        state: present
    # - name: install vim
    #   homebrew:
    #     name: "vim"
    #     state: present
    # - name: install neovim
    #   homebrew:
    #     name: "neovim"
    #     state: present
    # - name: install emacs-plus
    #   homebrew:
    #     name: "emacs-plus"
    #     state: present
    - name: install tmux
      homebrew:
        name: "tmux"
        state: present
    # - name: install google-cloud-sdk
    #   homebrew:
    #     name: "google-cloud-sdk"
    #     state: present
    # - name: install 1password-cli
    #   homebrew:
    #     name: "1password-cli"
    #     state: present
    - name: install ffmpeg
      homebrew:
        name: "ffmpeg"
        state: present
    - name: install dep
      homebrew:
        name: "dep"
        state: present
    # Erlang & Elixir
    - name: install autoconf
      homebrew:
        name: "autoconf"
        state: present
    - name: install openssl@1.1
      homebrew:
        name: "openssl@1.1"
        state: present
    - name: install wxwidgets
      homebrew:
        name: "wxwidgets"
        state: present
    - name: install libxslt
      homebrew:
        name: "libxslt"
        state: present
    - name: install fop
      homebrew:
        name: "fop"
        state: present
