- hosts: localhost
  tasks:
    # install system tools
    - name: install htop
      homebrew:
        name: "htop"
        state: present
    - name: install tmux
      homebrew:
        name: "tmux"
        state: present
    - name: install watch
      homebrew:
        name: "watch"
        state: present
    - name: install fonts
      homebrew:
        name: "font-hack-nerd-font"
        state: present
    # tmux deps
    - name: install utf8proc
      homebrew:
        name: "utf8proc"
        state: present
    # golang deps
    - name: install coreutils
      homebrew:
        name: "coreutils"
        state: present
    # erlang deps
    - name: install autoconf
      homebrew:
        name: "autoconf"
        state: present
    - name: install openssl@1.1
      homebrew:
        name: "openssl@1.1"
        state: present
    - name: install wxwidgets
      homebrew:
        name: "wxwidgets"
        state: present
    - name: install libxslt
      homebrew:
        name: "libxslt"
        state: present
    - name: install fop
      homebrew:
        name: "fop"
        state: present
    # ruby deps
    - name: install openssl@1.1
      homebrew:
        name: "openssl@1.1"
    - name: install readline
      homebrew:
        name: "readline"
    - name: install libyaml
      homebrew:
        name: "libyaml"
    - name: install gmp
      homebrew:
        name: "gmp"
    - name: install mas
      homebrew:
        name: "mas"
