- hosts: localhost
  tasks:
    - homebrew_tap:
        name: "d12frosted/emacs-plus"
        state: present
    - name: Install Packages
      homebrew:
        name: [
          "emacs-plus",
          "go",
          "neovim",
          "python",
          "python@2",
          "tmux",
          "yarn",
          "vim",
          "zsh"
        ]
        state: present
