- hosts: localhost
  become: true
  tasks:
    - name: "Install basic deps needed for install"
      apt:
        name:
          - locales
          - software-properties-common
          - tmux
          - zsh
          - emacs
        state: "present"

    - name: "Ensure locale exists"
      locale_gen:
        name: "en_US.UTF-8"
        state: "present"

    - name: "Set default locale"
      template:
        src: "etc/default/locale.j2"
        dest: "/etc/default/locale"
        owner: "root"
        group: "root"
        mode: 0644

    - name: "Download Microsoft apt repo deb"
      get_url:
        url: "https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb"
        dest: "/tmp/ansible-downloads-packages-microsoft-prod.deb"

    - name: "Add Microsoft apt repo"
      apt:
        deb: "/tmp/ansible-downloads-packages-microsoft-prod.deb"
        state: "present"

    - name: "Install powershell"
      apt:
        name: powershell
        update_cache: "yes"
        install_recommends: "yes"
        state: "present"

    #- name: "Add Docker apt key"
    #  apt_key:
    #    url: "https://download.docker.com/linux/ubuntu/gpg"
    #    state: "present"

    #- name: "Add Docker apt repo"
    #  apt_repository:
    #    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
    #    state: "present"

    #- name: "Install docker-compose"
    #  get_url:
    #    url: "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64"
    #    dest: "/usr/local/bin/docker-compose"
    #    mode: 0755

    # - name: "Install powershell"
    #   apt:
    #     name: powershell
    #     update_cache: "yes"
    #     install_recommends: "yes"
    #     state: "present"

    - name: "Install erlang deps"
      apt:
        name:
          - autoconf
          - build-essential
          - fop
          - libgl1-mesa-dev
          - libglu1-mesa-dev
          - libncurses-dev
          - libncurses5-dev
          - libpng-dev
          - libssh-dev
          - libwxgtk-webview3.0-gtk3-dev
          - libwxgtk3.0-gtk3-dev
          - libxml2-utils
          - m4
          - openjdk-11-jdk
          - unixodbc-dev
          - xsltproc
        update_cache: "yes"
        install_recommends: "yes"
        state: "present"

    - name: "Install elixir deps"
      apt:
        name:
          - inotify-tools
        update_cache: "yes"
        install_recommends: "yes"
        state: "present"

    - name: "Install golang deps"
      apt:
        name:
          - curl
          - coreutils
        update_cache: "yes"
        install_recommends: "yes"
        state: "present"

    - name: "Install ruby deps"
      apt:
        name:
          - autoconf
          - build-essential
          - libdb-dev
          - libffi-dev
          - libgdbm-dev
          - libgdbm6
          - libgmp-dev
          - libncurses5-dev
          - libreadline6-dev
          - libssl-dev
          - libyaml-dev
          - patch
          - rustc
          - uuid-dev
          - zlib1g-dev
        update_cache: "yes"
        install_recommends: "yes"
        state: "present"

    - name: "Install mosh dependencies"
      apt:
        name:
          - autoconf
          - build-essential
          - perl
          - protobuf-compiler
          - libprotobuf-dev
          - libncurses5-dev
          - zlib1g-dev
          - libutempter-dev
          - libssl-dev
        update_cache: "yes"
        install_recommends: "yes"
        state: "present"
