#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "onedark"
    background = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = false
    enable_statusline_display_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 15


## -- SpaceVim layer list start
[[layers]]
  name = "VersionControl"

[[layers]]
  name = "checkers"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "core#banner"

[[layers]]
  name = "core#statusline"

[[layers]]
  name = "core#tabline"

[[layers]]
  name = "core"

[[layers]]
  name = "debug"

[[layers]]
  name = "default"

[[layers]]
  name = "denite"

[[layers]]
  name = "edit"

[[layers]]
  name = "floobits"

[[layers]]
  name = "format"

[[layers]]
  name = "fzf"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "lang#WebAssembly"

[[layers]]
  name = "lang#autohotkey"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#elixir"

[[layers]]
  name = "lang#elm"

[[layers]]
  name = "lang#erlang"

[[layers]]
  name = "lang#extra"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#haskell"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#java"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#lua"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#ocaml"

[[layers]]
  name = "lang#perl"

[[layers]]
  name = "lang#plantuml"

[[layers]]
  name = "lang#puppet"

[[layers]]
  name = "lang#purescript"

[[layers]]
  name = "lang#python"

[[layers]]
  name = "lang#ruby"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#scala"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#swift"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "lang#vim"

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "lsp"
  filetypes = [
    "dockerfile",
    "go",
    "javascript",
    "python",
    "rust"
  ]

[[layers]]
  name = "leaderf"

[[layers]]
  name = "sudo"

[[layers]]
  name = "tags"

[[layers]]
  name = "tmux"

[[layers]]
  name = "tools#dash"

[[layers]]
  name = "tools"

[[layers]]
  name = "ui"

## -- SpaceVim layer list end
