[[ -s "$HOME/.bashrc" ]] && source "$HOME/.bashrc"
if [ -f "$HOME/google-cloud-sdk/completion.bash.inc" ]; then . "$HOME/google-cloud-sdk/completion.bash.inc"; fi

export PATH="$HOME/.cargo/bin:$PATH"
