alias vim='nvim'
alias emacsd="$HOME/.dotfiles/src/local/scripts/emacsdaemon.sh"

# Base16 Shell
BASE16_SHELL="$HOME/.dotfiles/src/github/chriskempson/base16-shell"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
    eval "$("$BASE16_SHELL/profile_helper.sh")"

export PATH="$HOME/.cargo/bin:$PATH"
