alias vim='nvim'
alias emacsd="$HOME/.dotfiles/src/local/scripts/emacsdaemon.sh"

export BASE16_SHELL="$HOME/.dotfiles/src/local/themes/dracula/dracula.sh"
source $BASE16_SHELL

export PATH="$HOME/.cargo/bin:$PATH"
