export PATH="$HOME/google-cloud-sdk/bin:$HOME/.cargo/bin:$HOME/go/bin:$HOME/.yarn/bin:$HOME/.local/bin:$HOME/.rvm/bin:$PATH"
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
export SHELL="$(which zsh)"
export TERM="xterm-256color"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US:en"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"
export GTAGSLABEL="pygments"
