export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="refined"
DISABLE_AUTO_UPDATE="true"

plugins=(
  git
)

source $ZSH/oh-my-zsh.sh

prompt_dir() {
    prompt_segment blue black "`basename ${PWD##*/}`"
}

if [ -f "$HOME/google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/google-cloud-sdk/completion.zsh.inc"; fi
